export const products = [
  {
    id: 1,
    category: "Cards",
    title: "Rounded Corner Sport UV Matt Lamination 400gsm",
    mainImage: "assets/img/product-images/p1.png",
    hoverImage: "assets/img/product-images/p1.png",
    rating: 5,
    newPrice: "AED-175",
    oldPrice: "AED-225",
    label: "",
    badge: "new",
    weight: ""
  },
  {
    id: 2,
    category: "Flyers",
    title: "A5 Glossy Flyers – 130gsm",
    mainImage: "assets/img/product-images/p2.png",
    hoverImage: "assets/img/product-images/p2.png",
    rating: 4,
    newPrice: "AED-95",
    oldPrice: "AED-130",
    label: "",
    badge: "sale",
    weight: ""
  },
  {
    id: 3,
    category: "Bags",
    title: "Custom Kraft Shopping Bags",
    mainImage: "assets/img/product-images/p3.png",
    hoverImage: "assets/img/product-images/p3.png",
    rating: 5,
    newPrice: "AED-225",
    oldPrice: "AED-275",
    label: "",
    badge: "",
    weight: ""
  },
  {
    id: 4,
    category: "Stickers",
    title: "Premium Die-Cut Stickers – Gloss",
    mainImage: "assets/img/product-images/p4.png",
    hoverImage: "assets/img/product-images/p4.png",
    rating: 4,
    newPrice: "AED-60",
    oldPrice: "AED-80",
    label: "",
    badge: "",
    weight: ""
  },
  {
    id: 5,
    category: "Cards",
    title: "Gold Foil Business Cards – 400gsm",
    mainImage: "assets/img/product-images/p5.png",
    hoverImage: "assets/img/product-images/p5.png",
    rating: 5,
    newPrice: "AED-320",
    oldPrice: "AED-360",
    label: "",
    badge: "new",
    weight: ""
  },
  {
    id: 6,
    category: "Menus",
    title: "Tri-Fold Restaurant Menus – 300gsm",
    mainImage: "assets/img/product-images/p6.png",
    hoverImage: "assets/img/product-images/p6.png",
    rating: 4,
    newPrice: "AED-185",
    oldPrice: "AED-210",
    label: "",
    badge: "",
    weight: ""
  },
  {
    id: 7,
    category: "Envelopes",
    title: "DL Envelopes with Window",
    mainImage: "assets/img/product-images/p7.png",
    hoverImage: "assets/img/product-images/p7.png",
    rating: 4,
    newPrice: "AED-75",
    oldPrice: "AED-95",
    label: "",
    badge: "sale",
    weight: ""
  },
  {
    id: 8,
    category: "Table Mat",
    title: "Disposable Table Mats – A3",
    mainImage: "assets/img/product-images/p8.png",
    hoverImage: "assets/img/product-images/p8.png",
    rating: 5,
    newPrice: "AED-90",
    oldPrice: "AED-105",
    label: "",
    badge: "",
    weight: ""
  }
];
